#!/bin/bash

# Execute this script in the ./zout directory containing viewODE stride 
# joint debug output file generated by executing viewODE as:
#
#   $ mkdir zout (if it does not already exist)
#   $ python3 viewODE.py 6.0 J:D:Z:0.5:Y:W 1>zout/stride_joints_output.txt
#
# then change to zout subdirectory and invoke this script:
#
#   $ cd zout
#   $ ./extract_stride_joints_data.sh
#
# Use gnuplot to display stride right and left leg joints data:
#
#   $ gnuplot -p R_foot-R_ballUniversal_gnuplot.dat
#   $ gnuplot -p L_foot-L_ballUniversal_gnuplot.dat
#   $ gnuplot -p R_shin-R_ankleUniversal_gnuplot.dat
#   $ gnuplot -p L_shin-L_ankleUniversal_gnuplot.dat
#   $ gnuplot -p R_thigh-R_kneeHinge_gnuplot.dat
#   $ gnuplot -p L_thigh-L_kneeHinge_gnuplot.dat
#   $ gnuplot -p pelvis-R_hipUniversal_gnuplot.dat
#   $ gnuplot -p pelvis-L_hipUniversal_gnuplot.dat
#
# NOTE: The previous two steps are performed by executing
# the ./util/gnuplot_stride_joints_data.sh script from
# within the ./zout subdirectory.

JOINTS_DATA_TXT_FILE=stride_joints_output.txt

BALL_JOINTS="R_foot-R_ballUniversal L_foot-L_ballUniversal"
ANKLE_JOINTS="R_shin-R_ankleUniversal L_shin-L_ankleUniversal"
KNEE_JOINTS="R_thigh-R_kneeHinge L_thigh-L_kneeHinge"
HIP_JOINTS="pelvis-R_hipUniversal pelvis-L_hipUniversal"

JOINTS_LIST="$BALL_JOINTS $ANKLE_JOINTS $KNEE_JOINTS $HIP_JOINTS"
for JOINT in $JOINTS_LIST
do
  grep "$JOINT" "$JOINTS_DATA_TXT_FILE" > "${JOINT}.txt"
done

for JOINT in $JOINTS_LIST
do
  python2 ../util/txt2dat.py "${JOINT}.txt" "$JOINT" "0"
done
