#!/bin/bash

# Execute this script in ./zout subdirectory containing viewODE stride
# action debug output file generated by executing viewODE as shown below
# starting in directory containing the viewODE.py file:
#
#   $ mkdir zout (if it does not already exist)
#   $ python3 viewODE.py 6.0 H:D:Z:0.5:Y:W 1>zout/stride_action_output.txt
#
# then change to zout subdirectory and invoke this script:
#
#   $ cd zout
#   $ ../util/extract_stride_action_data.sh
#
# Use gnuplot to display stride right and left leg motor action data:
#
#   $ gnuplot -p right_leg_gnuplot.dat
#   $ gnuplot -p left_leg_gnuplot.dat
#
# NOTE: The previous two steps are performed by executing
# the ./util/gnuplot_stride_action_data.sh script from
# within the ./zout subdirectory.

ACTION_DATA_TXT_FILE=stride_action_output.txt

LEG_LIST="right_leg left_leg"

for LEG in $LEG_LIST
do
  grep "$LEG" "$ACTION_DATA_TXT_FILE" > "${LEG}.txt"
done

for LEG in $LEG_LIST
do
  python3 ../util/txt2dat.py "${LEG}.txt" "$LEG" "0"
done
