#!/bin/bash

# Execute this script in ./zout subdirectory containing viewODE stride
# action debug output file generated by executing viewODE as shown below
# starting in directory containing the viewODE.py file:
#
#   $ mkdir zout (if it does not already exist)
#   $ python3 viewODE.py 6.0 H:D:Z:0.5:Y:W 1>zout/stride_action_output.txt
#
# then change to zout subdirectory and invoke this script:
#
#   $ cd zout
#   $ ../util/gnuplot_stride_action_data.sh

# Extract leg motor data from striding actiom debug output file.
../util/extract_stride_action_data.sh

# Invoke gnuplot to render and save plots as JPEG images.
PLOT_LIST="right_leg left_leg"
for P in $PLOT_LIST
do
  PLOT_DAT=\'${P}_gnuplot.dat\'
  PLOT_IMG=\'${P}.jpg\'
  PLOT_DAT_CMDS="load $PLOT_DAT; set grid; replot"
  PLOT_IMG_CMDS="set term push; set term jpeg; set output $PLOT_IMG; replot"
  taskset -c 2 gnuplot -e "$PLOT_DAT_CMDS; $PLOT_IMG_CMDS; set term pop; quit"
done
