#!/bin/bash

#FILE:  jpgtomp4.sh
#DATE:  05 AUG 2012
#AUTH:  G. E. Deschaines
#DESC:  Converts a sequence of JPG files to an MP4 video file.
#NOTE:  Requires ffmpeg

# Execute this script in ./zimg subdirectory containing viewODE rendering
# image capture JPEG files generated by executing viewODE as shown below
# starting in directory containing the viewODE.py file:
#
#   $ mkdir zimg
#   $ python viewODE.py
#   $ Z
#   $ I
#   .
#   .
#   .
#   $ I
#   $ Esc

echo "Creating MP4 video file:  img_anim.mp4"
ffmpeg -f image2 -r 12.5 -i img_%04d.jpg -vcodec libx264 -crf 18 -pix_fmt yuv420p img_anim.mp4
exit 0
