#!/bin/bash

#FILE:  jpgtogif.sh
#DATE:  05 AUG 2012
#AUTH:  G. E. Deschaines
#DESC:  Converts a sequence of JPEG files to GIF files and merges
#       the GIF files into an animated GIF file.
#NOTE:  Requires the ImageMagick convert program.

# Execute this script in ./zimg subdirectory containing viewODE rendering
# image capture JPEG files generated by executing viewODE as shown below
# starting in directory containing the viewODE.py file:
#
#   $ mkdir zimg
#   $ python viewODE.py
#   $ Z
#   $ I
#   .
#   .
#   .
#   $ I
#   $ Esc

# Get list of JPEG files.

JPG_LIST=(`ls img_0???.jpg`)
if [ "${#JPG_LIST[*]}" == "0" ]
then
  echo "error:  No JPG files in present working directory."
  exit -1
fi

# Convert each JPG file into a GIF file.

GIF_LIST=""
for FILE in ${JPG_LIST[@]}
do
  NAME=${FILE%.jpg}
  echo "converting:  $FILE"
  convert $FILE $NAME.gif
  GIF_LIST="$GIF_LIST $NAME.gif"
done

# Merge all GIF files into the animated gif file.

echo "Creating animated gif file:  img_anim.gif"
convert -dispose None -delay 8 $GIF_LIST -loop 0 img_anim.gif

exit 0
